  db:
    image: postgres
    container_name: connect1
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5435:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 9345:8080
